name: fast_barcode_scanner
description: A fast barcode scanner using MLKit on Android and AVFoundation on iOS.
version: 2.3.0
publish_to: http://nexus.gojitsu.com:7777
homepage: https://github.com/jhoogstraat/fast_barcode_scanner
repository: https://github.com/jhoogstraat/fast_barcode_scanner

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  fast_barcode_scanner_platform_interface:
    hosted:
      name: fast_barcode_scanner_platform_interface
      url: http://nexus.gojitsu.com:7777
    version: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.jhoogstraat.fast_barcode_scanner
        pluginClass: FastBarcodeScannerPlugin
      ios:
        pluginClass: FastBarcodeScannerPlugin
